import "../styles/globals.css"

import Navbar from "@/features/Navbar";
import Footer from "@/features/Footer";
import { NavbarContextProvider } from "@/context/NavbarConext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
		<html lang='en'>
			<body>
				<NavbarContextProvider>
					<Navbar />
				</NavbarContextProvider>
				<main>
					{children}
				</main>
				<Footer />
			</body>
		</html>
	)
}
