import "../styles/globals.css"

import Navbar from "@/features/Navbar";
import Footer from "@/features/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
